### ISSUE TITLE
Canvas Size

### ISSUE THREAD

**Issue by austinklenk** [Brantron/john_hancock#9]
I tried doing a canvas width with css say 500px, it throws off the drawing on the canvas.
how can i make the canvas size bigger without throwing off the drawing points.

css div   
```
canvas#JohnHancock-canvas {
    background-color: #fff;
    border: 1px solid #000;
    width: 400px;
  }

```
help..

**Comment by Brantron** [comment]
Hey, looking now!

**Comment by Brantron** [comment]
Please install v.0.1.2 which I just pushed. This updates the canvas JS library and adds some sizing fixes.

**Comment by austinklenk** [comment]
Thanks for the quick reply! that works perfectly!
